### ISSUE TITLE
An error occurred initializing YouTube search and this functionality will not be available

### ISSUE THREAD

**Issue by rishi0808** [SegiH/You2Me#20]
Hi, im trying to run this software locally and am currently getting this error after putting my API key in 

An error occurred initializing YouTube search and this functionality will not be available, any ideas whats causing it?

**Comment by SegiH** [comment]
Yea. I know what that means.

Are you using Docker?

**Comment by rishi0808** [comment]
I am!, I've been following the instructions to the tee and it keeps saying that search failed to initialise, just tried starting and running via the docker settings at the top of the install file and doesnt seem to let me search against a URL to find matches

**Comment by SegiH** [comment]
I just realize that you are using a version of my app that's deprecated. The thing is, my other repo and most other projects that rely on YouTube-dl are currently not working because of API changes that Google made that has broken youtube-dl.

Check out the repo metube for a docker based solution that does work.
